---

- name: Remove OpenJDK 1.7 Java Development Kit (JDK) from a Centos-based cluster
  hosts: dl-cluster
  sudo: yes
  tasks:
    - yum: update_cache=yes cache_valid_time=3600
    - yum: name=java-1.7.0-openjdk-devel state=absent

  
