---

- hosts: sw-11
  sudo: yes
  vars:
    hue_version: hue-3.8.1
    hue_tarball: hue-3.8.1.tgz
    hue_tmp_dir: /tmp
    hue_drop: "{{ hue_tmp_dir }}/{{ hue_tarball }}"
    hue_install_dir: /opt/hue-3.8.1
  tasks:
    - include: plays/remove/hue.yml
