---

- name: Install Pertino clients on the dl-cluster
  hosts: sw-21
  sudo: yes
  tasks:
    # install Pertino GPG signing key
    - apt_key: url=http://reposerver.pertino.com/Pertino-GPG-Key.pub
    # add the Pertino repo server to the distribution source list
    - script: ./scripts/pertino_repo.sh
    # install the Pertino client
    - apt: update_cache=true cache_valid_time=3600 name=pertino-client state=present
    - command: 'ifconfig pertino0'
      register: ifconfig
    - debug: var=ifconfig
  
