---

- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    - ami_id: ami-dceed0b4
    - vpc_subnet_id: subnet-05fe9672

  tasks:
    - name: provision a set of instances
      ec2:
        key_name: stillwater
        group: home
        instance_type: m3.xlarge
        image: "{{ ami_id }}"
        wait: true
        exact_count: 2
        count_tag:
          Name: Datalake
        instance_tags:
          Name: Datalake
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        assign_public_ip: yes
      register: ec2

    - name: Add all instance public IPs to a host group
      add_host: hostname={{ item.public_ip }} groups=ec2hosts
      with_items: ec2.instances


- hosts: ec2hosts
  user: ubuntu
  gather_facts: true

  tasks:
    - command: /bin/ls -l
      register: files

    - debug: var=files.stdout
