---

- name: reboot the cluster
  hosts: all
  sudo: yes
  gather_facts: no
  tasks:
    - name: Restart all machines in the cluster
      command: /sbin/shutdown -r now "Ansible triggered reboot"
      async: 0
      poll: 0
      ignore_errors: true
    - name: Wait for servers to come back
      local_action: wait_for host={{ inventory_hostname }}
                    state=started
      sudo: false
  
